title: My Awesome Site
description: My personal blog about coding

github:
  is_project_page: false
  
collections:
  genesis:
    output: true
    permalink: /genesis/:name/

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
